language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO=1.10
  - DJANGO=1.11

branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install -r requirements-dev.txt

before_script:
  - cd tests
  - export DJANGO_SETTINGS_MODULE=testsapp.settings

script:
  - coverage run --source=musette manage.py test

after_success:
  coveralls