# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name_zh', models.CharField(help_text='栏目名', max_length=255)),
                ('subject_name_en', models.CharField(help_text='栏目名', max_length=255)),
                ('parent', models.IntegerField(help_text='父栏目')),
                ('order', models.IntegerField(default=0, help_text='排序', null=True)),
                ('is_visiable', models.BooleanField(default=0, help_text='是否显示')),
                ('is_removed', models.BooleanField(default=0, help_text='是否删除')),
            ],
        ),
    ]
